### ISSUE TITLE
Broken on current version of LIEF?

### ISSUE THREAD

**Issue by esemeniuc** [otter-sec/bn-ebpf-solana#2]
Running into the following on Linux with python 3.12. Tried LIEF 0.15.1 and 0.16.dev0
```
[BinaryView.ElfView] Detected Little Endian endian ELF
[BinaryView.ElfView] Found string table of size 0xaa at offset 0x4cfc0
[BinaryView.ElfView] Found string table of size 0x48 at offset 0x51240
[BinaryView.ElfView] Found string table of size 0xaa at address 0x4cfc0
[BinaryView.ElfView] ELF architecture 247 is not supported
[Default] BinaryView of type 'ELF' failed to initialize!
[Default] init
[Default] LIEF does not support relocation for 'BPF'
[Default] Traceback (most recent call last):
[Default]   File "/opt/binaryninja/plugins/../python/binaryninja/binaryview.py", line 3405, in _init
[Default]     return self.init()
[Default]            ^^^^^^^^^^^
[Default]   File "/home/eric/.binaryninja/plugins/bn-ebpf-solana/solanaview.py", line 92, in init
[Default]     if s.type == lief.ELF.SEGMENT_TYPES.LOAD:
[Default]                  ^^^^^^^^^^^^^^^^^^^^^^
[Default] AttributeError: module 'lief._lief.ELF' has no attribute 'SEGMENT_TYPES'
[Default] BinaryView of type 'Solana' failed to initialize!
```

Tried
```
pip install --index-url https://lief.s3-website.fr-par.scw.cloud/latest lief
```
and regular `pip install lief`

**Comment by renato-osec** [comment]
Fixed with #3
